import json
import os
from pathlib import Path

import pytest

from utils.api_client import APIClient

SCHEMAS_DIR = Path(__file__).resolve().parent.parent / "schemas"


@pytest.fixture(scope="session")
def api() -> APIClient:
    return APIClient()


@pytest.fixture(scope="session")
def auth_token(api: APIClient) -> str:
    resp = api.post("/auth/login", {
        "username": "emilys",
        "password": "emilyspass",
        "expiresInMins": 30,
    })
    assert resp.status_code == 200
    return resp.json()["accessToken"]


@pytest.fixture(scope="session")
def load_schema():
    """Reads a schema from schemas/. Was copy-pasted into three test modules."""
    def _load(name: str) -> dict:
        with open(SCHEMAS_DIR / name) as f:
            return json.load(f)
    return _load


# ---------------------------------------------------------------------------
# Report presentation
#
# The published report is linked from my portfolio, and pytest-html titles the
# page after the output file  so it read "index.html" to anyone who opened it.
# These three hooks give it a name, say which commit and run produced it, and
# drop the environment rows that are noise on a hosted runner.
# ---------------------------------------------------------------------------

REPO_URL = "https://github.com/Priya123z/api-test-pytest"


def pytest_html_report_title(report):
    report.title = "REST API Test Suite  Priya Bhagoriya"


def pytest_metadata(metadata):
    # JAVA_HOME and the plugin list say nothing about this suite.
    for noise in ("JAVA_HOME", "Plugins"):
        metadata.pop(noise, None)

    metadata["Suite"] = "43 tests over CRUD and auth, with JSON Schema contracts"
    metadata["API under test"] = os.environ.get("BASE_URL", "https://dummyjson.com")
    metadata["Repository"] = REPO_URL

    sha = os.environ.get("GITHUB_SHA")
    if sha:
        metadata["Commit"] = f"{REPO_URL}/commit/{sha}"

    run_id = os.environ.get("GITHUB_RUN_ID")
    if run_id:
        metadata["CI run"] = f"{REPO_URL}/actions/runs/{run_id}"
        metadata["Triggered by"] = os.environ.get("GITHUB_EVENT_NAME", "unknown")


def pytest_html_results_summary(prefix):
    run_id = os.environ.get("GITHUB_RUN_ID")
    where = (
        f'run <a href="{REPO_URL}/actions/runs/{run_id}">#{os.environ.get("GITHUB_RUN_NUMBER", run_id)}</a>'
        if run_id else "a local run"
    )
    prefix.append(
        "<p>Every response below is validated against a JSON Schema in "
        f'<a href="{REPO_URL}/tree/main/schemas"><code>schemas/</code></a>, so a renamed '
        "field fails the build instead of quietly passing on a 200. "
        f"Generated by {where}  see the "
        f'<a href="{REPO_URL}">repository</a>.</p>'
    )
