import json
import os
from pathlib import Path

import pytest

from utils.api_client import APIClient

SCHEMAS_DIR = Path(__file__).resolve().parent.parent / "schemas"


@pytest.fixture(scope="session")
def api():
    return APIClient()


@pytest.fixture(scope="session")
def load_schema():
    """Reads a schema from schemas/. Was copy-pasted into three test modules."""
    def _load(name):
        with open(SCHEMAS_DIR / name) as f:
            return json.load(f)
    return _load


# ---------------------------------------------------------------------------
# Report presentation
#
# The published report is linked from my portfolio, and pytest-html titles the
# page after the output file, so it read "index.html" to anyone who opened it.
# These three hooks give it a name, say which commit and run produced it, and
# drop the environment rows that are noise on a hosted runner.
# ---------------------------------------------------------------------------

REPO_URL = "https://github.com/Priya123z/api-test-pytest"


def pytest_html_report_title(report):
    report.title = "REST API Test Suite, by Priya Bhagoriya"


def pytest_metadata(metadata):
    # JAVA_HOME and the plugin list say nothing about this suite.
    for noise in ("JAVA_HOME", "Plugins"):
        metadata.pop(noise, None)

    metadata["Suite"] = "CRUD and auth flows, with JSON Schema contracts"
    metadata["API under test"] = os.environ.get("BASE_URL", "https://dummyjson.com")
    metadata["Repository"] = REPO_URL

    sha = os.environ.get("GITHUB_SHA")
    if sha:
        metadata["Commit"] = f"{REPO_URL}/commit/{sha}"

    run_id = os.environ.get("GITHUB_RUN_ID")
    if run_id:
        metadata["CI run"] = f"{REPO_URL}/actions/runs/{run_id}"
        metadata["Triggered by"] = os.environ.get("GITHUB_EVENT_NAME", "unknown")


def pytest_html_results_summary(prefix):
    run_id = os.environ.get("GITHUB_RUN_ID")
    where = (
        f'run <a href="{REPO_URL}/actions/runs/{run_id}">#{os.environ.get("GITHUB_RUN_NUMBER", run_id)}</a>'
        if run_id else "a local run"
    )
    prefix.append(
        "<p>The user list, a single user, a created user and a login are each "
        "validated against a JSON Schema in "
        f'<a href="{REPO_URL}/tree/main/schemas"><code>schemas/</code></a>, so a renamed '
        "field fails the build instead of quietly passing on a 200. The error paths "
        "are asserted on status and message, because there is no contract to hold a "
        f"404 to. Generated by {where}. See the "
        f'<a href="{REPO_URL}">repository</a>.</p>'
    )
